### ISSUE TITLE
Model Details 

### ISSUE THREAD

**Issue by Devil-Ideal** [buxiangzhiren/VD-IT#9]
Hi! Your work is indeed awesome. However, I have some questions about two key implementations. Could you please provide more details about the noise prediction—why can it replace Gaussian noise? And how are the visual features and unsampled masks combined—through convolution layers?

**Comment by buxiangzhiren** [comment]
In our implementation, we aimed to reduce some of the randomness introduced by directly adding Gaussian noise, as typically done in diffusion forward processes. We employed prompt tuning to make the noise prediction trainable. This allows it to functionally replace Gaussian noise while still conditioning on the input data.

However, at this stage, it can no longer be considered true “noise” in the conventional sense because it is designed to condition and align with the input data rather than being purely stochastic. We think it introduces less uncertainty compared to traditional Gaussian noise, which aligns better with our goal of getting detailed segmentation masks.

**Comment by buxiangzhiren** [comment]
As to the second question, are you asking dynamic conv layers?

**Comment by Devil-Ideal** [comment]
> As to the second question, are you asking dynamic conv layers?

It's about the description "Before the first and third rounds of upsampling, they are combined with visual features Fv to achieve high-quality masks" in the paper. I'm not sure about the meaning of  "combined".

**Comment by buxiangzhiren** [comment]
It involves concatenating the mask and visual features, passing them through convolutional layers, and then performing upsampling.

**Comment by Devil-Ideal** [comment]
> It involves concatenating the mask and visual features, passing them through convolutional layers, and then performing upsampling.

Thank you for prompt reply!
